server:
  port: 9090
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
